"""Build the static frontend bundle for a host that is not the API host.

The page in static/ is the single source of truth and links its assets
relatively, so the only thing that has to change for a split deployment is the
API origin in config.js. This copies the four files into deploy/dist/ with that
origin written in, plus the IIS web.config.

    python deploy/build_frontend.py https://resume-depth.onrender.com

Then upload everything inside deploy/dist/ to the web root of the static host.
"""

import hashlib
import re
import shutil
import sys
from pathlib import Path

DEPLOY_DIR = Path(__file__).parent
STATIC_DIR = DEPLOY_DIR.parent / "static"
DIST_DIR = DEPLOY_DIR / "dist"

ASSETS = ["index.html", "app.js", "style.css"]

CONFIG_TEMPLATE = '''/* Generated by deploy/build_frontend.py - do not edit by hand.
 * The origin of the FastAPI backend this page talks to. It must also appear in
 * the backend's ALLOWED_ORIGINS or the browser will block every call. */
window.API_BASE = "{api_base}";
'''


def stamp_assets(dist: Path) -> None:
    """Append a content hash to each asset link in index.html.

    The host sends no Cache-Control, so a browser that has already seen
    "app.js" keeps using its copy and never notices a redeploy - which is how a
    fixed button can be live on the server and still dead in the browser. The
    hash changes only when the file changes, so a deploy that touches nothing
    leaves the caching intact.
    """
    page = dist / "index.html"
    html = page.read_text(encoding="utf-8")

    for name in ("style.css", "config.js", "app.js"):
        asset = dist / name
        if not asset.exists():
            continue
        digest = hashlib.sha256(asset.read_bytes()).hexdigest()[:10]
        # match the bare filename in href="" or src="", with or without an
        # existing ?v= so re-running the build replaces rather than stacks
        html = re.sub(rf'((?:href|src)="{re.escape(name)})(\?v=[^"]*)?"',
                      rf'\1?v={digest}"', html)

    page.write_text(html, encoding="utf-8")

def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        print(__doc__)
        return 2

    api_base = args[0].strip().rstrip("/")
    if not api_base.startswith(("http://", "https://")):
        print(f"error: API base must start with http:// or https:// - got {api_base!r}")
        return 2
    if api_base.endswith("/api"):
        print("error: give the origin only, without the /api suffix")
        return 2

    if DIST_DIR.exists():
        shutil.rmtree(DIST_DIR)
    DIST_DIR.mkdir(parents=True)

    for name in ASSETS:
        shutil.copy2(STATIC_DIR / name, DIST_DIR / name)
    (DIST_DIR / "config.js").write_text(
        CONFIG_TEMPLATE.format(api_base=api_base), encoding="utf-8")

    # web.config is deliberately NOT shipped by default. apptwo.gorecruitai.com
    # already has one carrying a rewrite rule that keeps /api routed to the
    # ASP.NET application beside this page; overwriting it would drop that for
    # nothing, since this page needs no routing of its own. Pass --with-web-config
    # only when putting the page on a host that has none.
    if "--with-web-config" in sys.argv:
        shutil.copy2(DEPLOY_DIR / "web.config", DIST_DIR / "web.config")

    stamp_assets(DIST_DIR)

    print(f"built {DIST_DIR} against {api_base}")
    for path in sorted(DIST_DIR.iterdir()):
        print(f"  {path.name:14} {path.stat().st_size:>7,} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
